#+TITLE: NixOS dotfiles
#+AUTHOR: Riyyi
#+LANGUAGE: en
#+OPTIONS: toc:nil

My attempt at dotfiles in NixOS.

** Bootstrap

Setting up a new machine only takes a couple of steps.

- boot into NixOS ISO
- run =passwd=
- (optional) log into the machine via SSH: =ssh nixos@<ip>=
- run
#+BEGIN_SRC sh
nix-shell -p git --command "nix run --experimental-features 'nix-command flakes' --no-write-lock-file --refresh github:riyyi/dotfiles-nix"
#+END_SRC
- run =./push.sh= from your existing machine
- reboot
- run =switch=

*** Additional configuration

I'm using ZFS on my NAS. To create the ZFS pool, run the following commands.

#+BEGIN_SRC sh
nix-shell -p git --command "git clone https://github.com/riyyi/dotfiles-nix ~/dotfiles"
sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko/latest -- --mode destroy,format,mount ~/dotfiles/profiles/nixos-nas/disko-mount.nix
#+END_SRC

To properly detach the ZFS pool, these commands need to be run before reboot!

#+BEGIN_SRC sh
sudo zfs unmount -a
sudo zpool export znas
#+END_SRC

** Structure of the repo

Rough outline of the repo files.

#+BEGIN_SRC
.
├── hosts/
│   ├── common/
│   │   └── <modules>
│   ├── darwin/
│   │   └── <modules>
│   ├── nixos/
│   │   └── <modules>
│   └── profiles/
│       └── <profile>
│           └── <modules>
├── modules/
│   ├── common/
│   │   └── <modules>
│   ├── darwin/
│   │   └── <modules>
│   ├── home-manager/
│   │   └── <modules>
│   └── nixos/
│       └── <modules>
├── overlays/
├── sops/
│   ├── secrets/
│   │   └── secrets.yaml
│   └── .sops.yaml
├── flake.nix
├── install.sh
├── push.sh
└── shell.nix
#+END_SRC

Interesting parts explained.

*** hosts

Stateful modules, separated by hostname.

**** profiles

This structure is used for system specific configuration, based on the hostname.\\
Each profile has its own =configuration.nix=, =disko.nix=, =settings.nix=, etc.

*** overlays

Overwrite flake package inputs.

*** SOPS

Secret encryption related files.

*** modules

Stateful modules, separated by evaluation scope.
Includes root services and home directory application configuration modules.
This is more general than =host= modules.

*** flake.nix

Entrypoint of the configuration.

*** install.sh

Bootstrap script to install the distro and push the configuration to it.\\
The script can be run from a booted NixOS ISO.

*** push.sh

Push your private SSH key to the system, of which the SOPS key will be derived.

*** shell.nix

Sets up a dev shell for REPL use, useful for debugging.

** Todo

v SSL cert
~ nextcloud
  v Samba
  ~ NFS
- ZFS rebuild array test
v ZFS test snapshots
v test jellyfin video transcode
v syncthing directory config
- jellyfun *arr (Jellyseerr)
  https://github.com/iankiller77/MyAnimeSync
  https://github.com/awesome-jellyfin/awesome-jellyfin?tab=readme-ov-file#-related
- disable "root" ssh access

*** macOS Todo

- =user/= behind option flags + default.nix
