keys:
  - &primary age1fpn5rg8679kc3m9fd5v6fg2tpnnudqumh4alj5mr7qnkra3g5cesdfqz9u
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops|sh)$
    key_groups:
      - age:
          - *primary
